services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: top_academy_backend_local
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - .env:/app/.env
      - db_data:/app/data
    environment:
      - DB_PATH=/app/data/journal_bot.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: top_academy_frontend_local
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  db_data:
