services:
  redis:
    image: redis:7-alpine
    container_name: top_academy_redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: top_academy_backend
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - .env:/app/.env
      - db_data:/app/data
    environment:
      - DB_PATH=/app/data/journal_bot.db
      - REDIS_URL=tcp://redis:6379
      - BOT_TOKEN=${BOT_TOKEN}
      - TMA_URL=${TMA_URL}
    depends_on:
      - redis
    networks:
      - app_network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: top_academy_frontend
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - app_network

  caddy:
    image: caddy:2-alpine
    container_name: top_academy_caddy
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    environment:
      - DOMAIN=${DOMAIN:-localhost}
    depends_on:
      - frontend
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
  caddy_data:
  caddy_config:
  redis_data:
