services:
  redis:
    image: redis:7-alpine
    container_name: top_academy_redis_local
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis_data_local:/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: top_academy_backend_local
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - .env:/app/.env
      - db_data:/app/data
    environment:
      - DB_PATH=/app/data/journal_bot.db
      - REDIS_URL=tcp://redis:6379
    depends_on:
      - redis

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: top_academy_frontend_local
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  db_data:

  redis_data_local:
