services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: top_academy_backend_dev
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - .env:/app/.env
      - db_data_dev:/app/data
    environment:
      - DB_PATH=/app/data/journal_bot.db
      - BOT_TOKEN=${BOT_TOKEN}
      - TMA_URL=${TMA_URL}
    networks:
      - app_network_dev

  frontend_dev:
    image: node:20-alpine
    container_name: top_academy_frontend_dev
    restart: unless-stopped
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - app_network_dev

networks:
  app_network_dev:
    driver: bridge

volumes:
  db_data_dev:

